### ISSUE TITLE
rc版本退出口袋登录后，再登录提示 请升级到最新版本

### ISSUE THREAD

**Issue by x12121** [duan602728596/qqtools#17]
rc版本退出口袋登录后，再登录提示 请升级到最新版本

**Comment by duan602728596** [comment]
先用测试版吧，rc版本的算法更新了，我还没来得及改







在 2020-07-23 14:49:36，"x12121" <notifications@github.com> 写道：

rc版本退出口袋登录后，再登录提示 请升级到最新版本

**Comment by x12121** [comment]
account是填写口袋的数字id吗？填写之后还是不播口袋房间消息

**Comment by x12121** [comment]
> 先用测试版吧，rc版本的算法更新了，我还没来得及改 在 2020-07-23 14:49:36，"x12121" <notifications@github.com> 写道： rc版本退出口袋登录后，再登录提示 请升级到最新版本 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

account是填写口袋的数字id吗？填写之后还是不播口袋房间消息

**Comment by duan602728596** [comment]
去48的直播网站，在浏览器的开发者工具内找到这个请求，返回来的就是




在 2020-07-24 10:13:29，"x12121" <notifications@github.com> 写道：

先用测试版吧，rc版本的算法更新了，我还没来得及改 在 2020-07-23 14:49:36，"x12121" notifications@github.com 写道： rc版本退出口袋登录后，再登录提示 请升级到最新版本 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

account是填写口袋的数字id吗？填写之后还是不播口袋房间消息

**Comment by duan602728596** [comment]
（要先用账号登陆）




去48的直播网站，在浏览器的开发者工具内找到这个请求，返回来的就是




在 2020-07-24 10:13:29，"x12121" <notifications@github.com> 写道：

先用测试版吧，rc版本的算法更新了，我还没来得及改 在 2020-07-23 14:49:36，"x12121" notifications@github.com 写道： rc版本退出口袋登录后，再登录提示 请升级到最新版本 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

account是填写口袋的数字id吗？填写之后还是不播口袋房间消息

**Comment by x12121** [comment]
> （要先用账号登陆） 去48的直播网站，在浏览器的开发者工具内找到这个请求，返回来的就是 在 2020-07-24 10:13:29，"x12121" <notifications@github.com> 写道： 先用测试版吧，rc版本的算法更新了，我还没来得及改 在 2020-07-23 14:49:36，"x12121" notifications@github.com 写道： rc版本退出口袋登录后，再登录提示 请升级到最新版本 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. account是填写口袋的数字id吗？填写之后还是不播口袋房间消息 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

填写了返回来的account数字，依然是不播口袋房间消息

**Comment by duan602728596** [comment]
rc版本的pa算法已经更新
